# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QEEMain
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(QEEMain.pri)

FORMS += \
    qeecv/settingsdialog.ui

HEADERS += \
    qeecv/settingsdialog.h

SOURCES += \
    qeecv/settingsdialog.cpp
